# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'SimpleTwitterClient' do
       pod "OAuthSwift", "~> 0.5.0"
end

target 'SimpleTwitterClientTests' do
       pod "OAuthSwift", "~> 0.5.0"
end

target 'SimpleTwitterClientUITests' do
       pod "OAuthSwift", "~> 0.5.0"
end

